version: '3.9'

services:
  ui:
    # image: siddhantprateek/clozette-ai:ui-0.1.0
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      - REACT_APP_API_ENDPOINT=http://localhost:7600
    ports:
      - "8090:80"

  api: 
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - MINIO_BUCKET_NAME
      - MINIO_HOST
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
      - DATABASE_URL
      - TIDB_HOST=localhost
      - TIDB_PORT=4000
      - TIDB_USERNAME=root
      - TIDB_PASSWORD=""
      - TIDB_DATABASE=test
      - TIDB_TABLENAME=product
      - PREMAI_API_KEY
      - PREM_LLM_MODEL=gpt-3.5-turbo
      - PREM_PROJECT_ID
      - SEARCH_API_BASE_URL
    ports:
      - "7600:7600"